// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {SP1PayVerifier} from "../src/SP1PayVerifier.sol";
import {MockVerifier} from "../src/MockVerifier.sol";
import {SP1Verifier} from "sp1-contracts/contracts/src/v6.1.0/SP1VerifierGroth16.sol";

/// @notice Verifies a REAL SP1 Groth16 proof of the R_pay genesis-branch
///         program against the real SP1VerifierGroth16 (no mocks, no
///         cheatcodes on the verification path). The proof fixture is
///         generated by research/m4b-groth16 (guest = R_pay genesis branch,
///         fixture witness cross-checked by confetti/relation.py::check_R_pay)
///         and committed at test/fixtures/rpay-groth16.json.
contract SP1PayVerifierTest is Test {
    SP1PayVerifier verifier;
    bytes32 vkey;
    uint256 delta;
    bytes32 nI;
    bytes32 cI;
    bytes32 root;
    bytes proof;

    function setUp() public {
        string memory json =
            vm.readFile(string.concat(vm.projectRoot(), "/test/fixtures/rpay-groth16.json"));
        vkey = vm.parseJsonBytes32(json, ".vkey");
        bytes memory publicValues = vm.parseJsonBytes(json, ".publicValues");
        proof = vm.parseJsonBytes(json, ".proof");
        (delta, nI, cI, root) =
            abi.decode(publicValues, (uint256, bytes32, bytes32, bytes32));

        // Real Groth16 verifier + real program vkey; MockVerifier only backs
        // the not-yet-ported relations.
        SP1Verifier sp1 = new SP1Verifier();
        verifier = new SP1PayVerifier(address(sp1), vkey, address(new MockVerifier()));
    }

    function test_realGroth16ProofVerifies() public view {
        assertTrue(verifier.verifyPayment(delta, nI, cI, root, proof));
    }

    function test_rejectsWrongStatement() public view {
        // Tamper each public input in turn — the pairing check must fail.
        assertFalse(verifier.verifyPayment(delta + 1, nI, cI, root, proof));
        assertFalse(
            verifier.verifyPayment(delta, keccak256("bad nullifier"), cI, root, proof)
        );
        assertFalse(
            verifier.verifyPayment(delta, nI, keccak256("bad commitment"), root, proof)
        );
        assertFalse(
            verifier.verifyPayment(delta, nI, cI, keccak256("bad root"), proof)
        );
    }

    function test_rejectsTamperedProof() public view {
        bytes memory bad = proof;
        bad[7] ^= 0x01; // flip a bit inside the gnark proof body
        assertFalse(verifier.verifyPayment(delta, nI, cI, root, bad));
    }

    function test_rejectsWrongVkey() public {
        SP1Verifier sp1 = new SP1Verifier();
        SP1PayVerifier wrong =
            new SP1PayVerifier(address(sp1), keccak256("some other program"), address(0));
        assertFalse(wrong.verifyPayment(delta, nI, cI, root, proof));
    }

    function test_fallbackRoutesOtherRelations() public view {
        // Not-yet-ported relations delegate to the mock on the local chain.
        assertTrue(verifier.verifyGenesisClose(bytes16(0), bytes32(0), bytes32(0), ""));
    }
}
